# --------- EVENT SINKS BEGIN CONFIG -------
eventSinks:
  - instance: !!com.telamin.mongoose.connector.file.FileMessageSink
      filename: ./data-in/midRate.jsonl
    name: midPrice-sink
    valueMapper: !!com.telamin.mongoose.example.pnl.helper.MapToJson {}

  - instance: !!com.telamin.mongoose.connector.file.FileMessageSink
      filename: ./data-in/trades.jsonl
    name: trades-sink
    valueMapper: !!com.telamin.mongoose.example.pnl.helper.MapToJson {}
# --------- EVENT SINKS END CONFIG ---------


# --------- EVENT HANDLERS BEGIN CONFIG ---------
eventHandlers:
  - agentName: processor-agent
    idleStrategy: !!com.fluxtion.agrona.concurrent.BackoffIdleStrategy {}
    eventHandlers:
      data-generator-processor:
        customHandler: !!com.telamin.mongoose.example.pnl.DataGeneratorProcessor
          pricePublishSleep: 500
          tradePublishSleep: 1_000
# --------- EVENT HANDLERS END CONFIG ---------